# Generated by Django 4.2 on 2023-05-13 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_activelisting_category_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelisting',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='on_watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
