# Generated by Django 4.2 on 2023-05-13 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelisting',
            name='watchers',
            field=models.ManyToManyField(blank=True, null=True, related_name='on_watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
